# Generated by Django 3.0.2 on 2020-02-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
